### ISSUE TITLE
Font Awesome connection time out

### ISSUE THREAD

**Issue by hchev001** [hchev001/UniPS#108]
For now I'm going to comment out the font awesome css. @mebra005 you tried to use the CDN now, but I'm getting time out errors and its making lauching the app slower. We may be better off just downloading the images and linking them as such. Or idk.

**Comment by fredlo2010** [comment]
hey peeps I know this is not my section but maybe this helps with Font-Awesome

http://stackoverflow.com/questions/38796541/how-to-add-font-awesome-to-angular-2-cli-project

Remember everything that's is added to the project has to be done through npm, bower or ng-cli or something like that. 

Also the CDN is expected to be cranky and slow because the contents have to be retrieved every time or expects the browser to cache it; but I guess since this is a auto-generated (SPA) the browser cannot cache it. 

Hope this helps

**Comment by hchev001** [comment]
Issue was fixed, thanks Alfredo
